-- 1. Tabla de Perfiles (extendiendo auth.users)
CREATE TABLE public.perfiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  rol TEXT NOT NULL DEFAULT 'jurado',
  nombre_completo TEXT,
  email TEXT,
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Asegurarse de que el RLS (Row Level Security) permita al service_role o usuarios acceder
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura pública de perfiles" ON public.perfiles FOR SELECT USING (true);

-- 2. Tabla de Criterios de Evaluación
CREATE TABLE public.criterios_evaluacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  peso_porcentual NUMERIC, -- Opcional
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.criterios_evaluacion ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura pública de criterios" ON public.criterios_evaluacion FOR SELECT USING (true);

-- Insertar algunos criterios de ejemplo
INSERT INTO public.criterios_evaluacion (nombre, descripcion, peso_porcentual) VALUES
('Diseño e Innovación', 'Qué tan novedoso y visualmente atractivo es el proyecto.', 30),
('Viabilidad Técnica', 'Factibilidad de implementación con los recursos actuales.', 30),
('Proyección y Escabilidad', 'Potencial de crecimiento y aplicación en el mundo real.', 40);

-- 3. Tabla de Votos de Jurado
CREATE TABLE public.votos_jurado (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jurado_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE NOT NULL,
  proyecto_id BIGINT REFERENCES public.proyectos(id) ON DELETE CASCADE NOT NULL,
  criterio_id BIGINT REFERENCES public.criterios_evaluacion(id) ON DELETE CASCADE NOT NULL,
  calificacion NUMERIC NOT NULL CHECK (calificacion >= 1 AND calificacion <= 10),
  fecha_voto TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Restricción UNIQUE para evitar doble voto por criterio en un proyecto
  UNIQUE (jurado_id, proyecto_id, criterio_id)
);

ALTER TABLE public.votos_jurado ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Jurados pueden ver sus propios votos" ON public.votos_jurado FOR SELECT USING (auth.uid() = jurado_id);
-- Permitir lectura para todos temporalmente (útil si hay un panel de admin de resultados global)
CREATE POLICY "Permitir lectura general de votos_jurado" ON public.votos_jurado FOR SELECT USING (true);
